# Generated by Django 3.1.3 on 2024-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=159)),
                ('author', models.CharField(max_length=159)),
                ('ISBN', models.CharField(max_length=159)),
                ('bookstore', models.CharField(max_length=159)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('image', models.CharField(max_length=159)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('description', models.CharField(max_length=159)),
                ('dat_e', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=159)),
                ('lname', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
                ('address', models.CharField(max_length=159)),
                ('department', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=159)),
                ('author', models.CharField(max_length=159)),
                ('ISBN', models.CharField(max_length=159)),
                ('location', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='mealplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=159)),
                ('loginid', models.CharField(max_length=159)),
                ('plan', models.CharField(max_length=159)),
                ('fro_m', models.CharField(max_length=159)),
                ('t_o', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='room_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=159)),
                ('lname', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
                ('loginid', models.CharField(max_length=159)),
                ('gender', models.CharField(max_length=159)),
                ('cost', models.IntegerField()),
                ('dat_e', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=159)),
                ('lname', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
                ('address', models.CharField(max_length=159)),
                ('city', models.CharField(max_length=159)),
                ('state', models.CharField(max_length=159)),
                ('zip', models.CharField(max_length=159)),
                ('gender', models.CharField(max_length=159)),
                ('loginid', models.CharField(max_length=159)),
                ('pass_word', models.CharField(max_length=159)),
                ('department', models.CharField(max_length=159)),
            ],
        ),
    ]
