# Generated by Django 3.1.3 on 2024-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=159)),
                ('name', models.CharField(max_length=159)),
                ('description', models.CharField(max_length=159)),
                ('dat_e', models.DateField()),
                ('eid', models.CharField(max_length=159)),
            ],
        ),
    ]
