# Generated by Django 3.1.3 on 2024-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bookevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='busticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_e', models.CharField(max_length=159)),
                ('cost', models.CharField(max_length=159)),
                ('dat_e', models.DateField()),
                ('loginid', models.DateField()),
            ],
        ),
    ]
