# Generated by Django 3.1.3 on 2024-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_busticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busticket',
            name='loginid',
            field=models.CharField(max_length=159),
        ),
    ]
