# Generated by Django 3.1.3 on 2024-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20240502_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='votesp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
